test_that("use", {
  # lp <- list_params("params/violinparams_test.json","violin_schema.json")
  # expect_type(lp,"list")
  expect_warning(p <- cm_ggviolin("params/violinparams_test.json"))
  expect_s3_class(p,"ggplot")
  p <- cm_ggviolin("../../../data/iris_vio_params.json")
  expect_s3_class(p,"ggplot")
  # lp <- list_params("params/BPermits_parameters.json","violin_schema.json")
  # # expect_type(lp,"list")
  # p <- cm_ggviolin("params/BPermits_parameters.json")
  # expect_s3_class(p,"ggplot")
})
