test_that("use", {
  lp <- list_params("params/violinparams_test.json","violin_schema.json")
  expect_type(lp,"list")
  p <- violin(lp)
  expect_s3_class(p,"ggplot")
  lp <- list_params("params/BPermits_parameters.json","violin_schema.json")
  # expect_type(lp,"list")
  p <- violin(lp)
  expect_s3_class(p,"ggplot")
})
